---
grails:
    profile: web
    codegen:
        defaultPackage: uk.org.nbn.places
    spring:
        transactionManagement:
            proxies: false
    gorm:
        # Whether to autowire entities. 
        # Disabled by default for performance reasons.
        autowire: false         
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: nbn-places
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    config:
        locations:
            - file:///data/nbn-places/config/nbn-places-config.properties
            - file:///data/nbn-places/config/nbn-places-config.yml
            - file:///data/nbn-places/config/nbn-places-config.groovy
    cors:
        enabled: true
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true
---
#Required so that the gbif-ecat library does not break the initialisation from its internal application.properties
app:
  name: nbn-places
  dataDir: /tmp/gbif-ecat
skin:
  layout: generic
  orgNameLong: National Biodiversity Network
  orgNameShort: NBN
  fluidLayout: false
bie:
  baseURL: http://localhost:8080
  searchPath: /search
  index:
    url: http://localhost:8090/bie-index
serverName: http://dev.ala.org.au:8080
projectNameShort: ALA
projectName: ALA
biocache:
    baseURL: "http://biocache.ala.org.au"
biocacheService:
    baseURL: http://biocache.ala.org.au/ws
    queryContext:
spatial:
    baseURL: http://spatial.ala.org.au
layersService:
    baseURL: http://spatial.ala.org.au/ws
ala:
    baseURL: http://ala.org.au
collectory:
    baseURL: http://collections.ala.org.au
regions:
    baseURL: http://regions.ala.org.au
alerts:
    baseURL: http://alerts.ala.org.au/ws/
search:
  facets: idxtype
image:
    thumbnailUrl: http://images.ala.org.au/image/proxyImageThumbnail?imageId=
map:
    default:
        id:
        token:
        url: https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png
        attr: Map data &copy; <a href='http://www.openstreetmap.org/copyright'>OpenStreetMap</a>, imagery &copy; <a href='http://cartodb.com/attributions'>CartoDB</a>
        domain: abcd
        colour: e6704c
        decimalLatitude: -25.61
        decimalLongitude: 134.35
        zoomLevel: 4
    simpleMapButton: false
    records:
      colour: e6704c
    env:
    #  legendtitle: Licence # legend title (this might be retrievable from messages.properties or from https://records-ws.nbnatlas.org/facets/i18n[locale].properties, but included here for simplicity)
    #if using automatic legend from biocache then add colormode and legendhidemaxrange option
    #  options: colormode:license,CC-BY,CC-BY-NC,CC0,OGC;name:circle;size:4;opacity:0.8
    #  legendhidemaxrange: false  #hide upper limit of cutpoints on map legend


    #if using custom legend add layerfq options, labels and colours (same number of each and | delimited)
       options: name:circle;size:4;opacity:0.8
    #layers:
    #  fqs: license:("CC-BY" OR "CC-BY-NC")|license:CC0
    #  labels: CC-BY*|CC0
    #  colours: E6704C|FFC0CB



bieService:
  queryContext:
languageCodesUrl: file:///data/places/config/languages.json
geocode.querySuffix:

admin_role: ROLE_ADMIN
allowedImageEditingRoles: ROLE_ADMIN
synonymsTypes: synonym
show:
    tabs: overview,gallery,taxa-list,records,data-partners
    additionalMapFilter:

---

hibernate:
  show_sql: false
  cache:
    queries: false
    use_second_level_cache: true
    use_query_cache: true
    region:
      factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

dataSource:
  pooled: true
  jmxExport: true
  driverClassName: com.mysql.jdbc.Driver
  username:
  password:
  properties:
    # http://www.grails.org/doc/latest/guide/single.html#dataSource
    # see http://tomcat.apache.org/tomcat-7.0-doc/jdbc-pool.html#Common_Attributes for more
    timeBetweenEvictionRunsMillis: 60000 # milliseconds (default: 5000)
    testOnBorrow: true # default: false
    testOnReturn: false # default: false
    testWhileIdle: true # default: false
    validationQuery: "SELECT 1" # default: null
    validationQueryTimeout: 10 # seconds (default: -1 i.e. disabled)
    validationInterval: 30000 # milliseconds, default is 30000 (30 seconds)
    removeAbandoned: true # # default: false
    removeAbandonedTimeout: 300 # seconds (default: 60)
    logAbandoned: true # adds some overhead to every borrow from the pool, disable if it becomes a performance issue
    logValidationErrors: true # default: false, logs validation errors at SEVERE
    # NOTE: removeAbandoned: true OR testWhileIdle: true enables the Pool Cleaner. There is a bug with the
    # pool cleaner which causes deadlocks when using older mysql jdbc drivers. This configuration has been
    # tested successfully with mysql:mysql-connector-java:5.1.34.
    # mysql jdbc connection properties - see http://dev.mysql.com/doc/connector-j/en/connector-j-reference-configuration-properties.html
    dbProperties:
      autoReconnect: true
      connectTimeout: 0
      useUnicode: true
      characterEncoding: "UTF-8"

environments:
  development:
    dataSource:
      dbCreate: "create"
      url: "jdbc:mysql://localhost/places"
      username: "root"
      password: "password"
  test:
    dataSource:
      dbCreate: "create"
      pooled: true
      driverClassName: "org.h2.Driver"
      username: "sa"
      password: ""
  production:
    dataSource:
      dbCreate: "update"
